# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0006_auto_20200824_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenscienceprogram',
            name='validity',
            field=models.CharField(choices=[(b'past', 'Past'), (b'current', 'Current')], db_index=True, default=1, max_length=7, verbose_name='Validity'),
            preserve_default=False,
        ),
    ]
