# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0008_auto_20200828_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capjournal',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'CAPjournal'},
        ),
        migrations.AlterModelOptions(
            name='citizenscienceprogram',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='educationalmaterial',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='educationalprogram',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='geminifocus',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'Gemini Focus', 'verbose_name_plural': 'Gemini Focus'},
        ),
        migrations.AlterModelOptions(
            name='handout',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='minisite',
            options={'ordering': ['-priority', 'id']},
        ),
        migrations.AlterModelOptions(
            name='mirror',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'Mirror'},
        ),
        migrations.AlterModelOptions(
            name='noaonewsletter',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'NOAO Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='electronicposter',
            options={'ordering': ['-priority', 'id']},
        ),
    ]
