# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-21 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0010_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminifocus',
            options={'ordering': ['-priority', '-id'], 'verbose_name': 'Gemini Focus', 'verbose_name_plural': 'Gemini Focus'},
        ),
        migrations.AlterModelOptions(
            name='mirror',
            options={'ordering': ['-priority', '-id'], 'verbose_name': 'Mirror'},
        ),
        migrations.AlterModelOptions(
            name='noaonewsletter',
            options={'ordering': ['-priority', '-id'], 'verbose_name': 'NOAO Newsletter'},
        ),
    ]
