# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0012_videobackground'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoBackground',
            new_name='VideoConferenceBackground',
        ),
    ]
