# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangoplicity.archives.translation
import djangoplicity.translation.fields
import djangoplicity.translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0015_auto_20211214_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTourProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Virtual Tour translation',
                'proxy': True,
                'indexes': [],
            },
            bases=('products2.virtualtour', djangoplicity.archives.translation.TranslationProxyMixin),
            managers=[
                ('translation_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='lang',
            field=djangoplicity.translation.fields.LanguageField(db_index=True, default=djangoplicity.translation.models._get_defaut_lang, max_length=7, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='products2.VirtualTour', verbose_name='Translation source'),
        ),
        migrations.AddField(
            model_name='virtualtour',
            name='translation_ready',
            field=models.BooleanField(default=False, help_text='When you check this box and save this translation, an automatic notification email will be sent.'),
        ),
    ]
