# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('products2', '0017_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='IndexItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('index_url', models.CharField(max_length=200, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('disabled', models.BooleanField()),
                ('title', models.CharField(max_length=256)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_indexitem', to='contenttypes.ContentType', verbose_name='content type')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products2.Index')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together=set([('site',)]),
        ),
    ]
