# Generated by Django 3.1 on 2025-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0020_lineart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineart',
            options={'ordering': ['title'], 'verbose_name': 'Line Art', 'verbose_name_plural': 'Line Art'},
        ),
    ]
